// Unit tests for scripts/write-build-info-asset.mjs.
//
// Runs under Node's built-in test runner: `node --test`. The script
// guards its CLI body behind an "invoked directly" check, so
// importing it as a module triggers no side effects.

import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { test } from 'node:test';

import { extractBuildInfoPayload, writeBuildInfoAsset } from './write-build-info-asset.mjs';

function makeTsSource(payload) {
  return (
    '// AUTO-GENERATED by scripts/write-build-info.mjs. Do not edit by hand.\n' +
    '// Regenerated on every build; gitignored.\n' +
    'export interface BuildInfo {\n' +
    '  readonly version: string;\n' +
    '  readonly sha: string;\n' +
    '  readonly branch: string;\n' +
    '  readonly builtAt: string;\n' +
    '  readonly repoUrl: string;\n' +
    '  readonly buildNumber: string;\n' +
    '}\n' +
    '\n' +
    'export const BUILD_INFO: BuildInfo = ' +
    JSON.stringify(payload, null, 2) +
    ';\n'
  );
}

const SAMPLE_PAYLOAD = Object.freeze({
  version: '0.30.0',
  sha: 'abcdef1234567890abcdef1234567890abcdef12',
  branch: 'main',
  builtAt: '2025-06-01T12:34:56.789Z',
  repoUrl: 'https://github.com/geevensingh/jotjson',
  buildNumber: '99',
});

test('extractBuildInfoPayload round-trips the prebuild TS literal', () => {
  const tsSource = makeTsSource(SAMPLE_PAYLOAD);
  const extracted = extractBuildInfoPayload(tsSource);
  assert.deepEqual(extracted, SAMPLE_PAYLOAD);
});

test('extractBuildInfoPayload rejects missing BUILD_INFO literal', () => {
  assert.throws(
    () => extractBuildInfoPayload('// no BUILD_INFO here\nexport const x = 1;\n'),
    /could not locate the BUILD_INFO literal/,
  );
});

test('extractBuildInfoPayload rejects non-string field values', () => {
  // Simulate a hypothetical future change to write-build-info.mjs
  // that emits a non-string `buildNumber` -- the asset writer must
  // refuse rather than silently shipping a malformed marker.
  const malformedPayload = { ...SAMPLE_PAYLOAD, buildNumber: 99 };
  const tsSource = makeTsSource(malformedPayload);
  assert.throws(
    () => extractBuildInfoPayload(tsSource),
    /BUILD_INFO\.buildNumber must be a string/,
  );
});

test('extractBuildInfoPayload rejects non-string input', () => {
  assert.throws(() => extractBuildInfoPayload(null), /tsSource must be a string/);
  assert.throws(() => extractBuildInfoPayload(undefined), /tsSource must be a string/);
});

test('writeBuildInfoAsset writes pretty JSON with trailing newline', () => {
  const tmp = mkdtempSync(join(tmpdir(), 'jotjson-build-info-asset-'));
  try {
    const tsPath = join(tmp, 'build-info.ts');
    const browserDir = join(tmp, 'dist', 'jotjson', 'browser');
    const jsonPath = join(browserDir, 'build-info.json');
    writeFileSync(tsPath, makeTsSource(SAMPLE_PAYLOAD));
    mkdirSync(browserDir, { recursive: true });

    const written = writeBuildInfoAsset({
      tsPath,
      browserDirectory: browserDir,
      jsonPath,
      logger: { log() {} },
    });

    assert.deepEqual(written, SAMPLE_PAYLOAD);
    const bytes = readFileSync(jsonPath, 'utf8');
    assert.equal(bytes.endsWith('\n'), true, 'expected trailing newline');
    assert.deepEqual(JSON.parse(bytes), SAMPLE_PAYLOAD);
    // Pretty-printed (multi-line)
    assert.equal(bytes.includes('\n  "version": "0.30.0"'), true);
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
});

test('writeBuildInfoAsset fails loud when dist directory is missing', () => {
  const tmp = mkdtempSync(join(tmpdir(), 'jotjson-build-info-asset-'));
  try {
    const tsPath = join(tmp, 'build-info.ts');
    writeFileSync(tsPath, makeTsSource(SAMPLE_PAYLOAD));
    // Do NOT create the browser directory.
    assert.throws(
      () =>
        writeBuildInfoAsset({
          tsPath,
          browserDirectory: join(tmp, 'dist', 'jotjson', 'browser'),
          jsonPath: join(tmp, 'dist', 'jotjson', 'browser', 'build-info.json'),
          logger: { log() {} },
        }),
      /does not exist.*ng build/i,
    );
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
});

test('writeBuildInfoAsset fails loud when build-info.ts is missing', () => {
  const tmp = mkdtempSync(join(tmpdir(), 'jotjson-build-info-asset-'));
  try {
    const browserDir = join(tmp, 'dist', 'jotjson', 'browser');
    mkdirSync(browserDir, { recursive: true });
    assert.throws(
      () =>
        writeBuildInfoAsset({
          tsPath: join(tmp, 'build-info.ts'),
          browserDirectory: browserDir,
          jsonPath: join(browserDir, 'build-info.json'),
          logger: { log() {} },
        }),
      /does not exist.*write-build-info\.mjs/i,
    );
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
});
